config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  root to: 'pages#home'
  resources :vacancies
  resources :posts, only: %i[new create destroy]
  resources :users, only: %i[show edit update], param: :name
  resources :events, only: :index
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  TYPE = %i[user company]
  mount_uploader :image, ImageUploader
  has_one :company
  has_one :user
  has_many :vacancies

  store_accessor :socials,
    :vk, :telegram, :dribble, :behance, :youtube, :twitter, :linkedln

  store_accessor :contacts,
    :link_1, :link_2, :link_3

  accepts_nested_attributes_for :user, :company

  after_initialize :set_socials_defaults

  private

  def set_socials_defaults
    return if !new_record? || self.socials.present?

    self.socials = {
      vk: nil,
      telegram: nil,
      dribble: nil,
      behance: nil,
      youtube: nil,
      twitter: nil,
      linkedln: nil
    }
  end

  def set_contacts_defaults
    return if !new_record? || self.contacts.present?

    self.contacts = {
      link_1: nil,
      link_2: nil,
      link_3: nil
    }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :city_vacancies, class_name: 'CityVacancy'
  has_many :vacancies, through: :city_vacancies

  # accepts_nested_attributes_for :vacancies
end

app/models/city_vacancy.rb
class CityVacancy < ApplicationRecord
  belongs_to :city
  belongs_to :vacancy
end

app/models/company.rb
class Company < ApplicationRecord
    belongs_to :account
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    mount_uploader :image, ImageUploader
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :skill_vacancies, class_name: 'SkillVacancy'
  has_many :vacancies, through: :skill_vacancies

  accepts_nested_attributes_for :vacancies
end

app/models/skill_vacancy.rb
class SkillVacancy < ApplicationRecord
  belongs_to :skill
  belongs_to :vacancy
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :account
    has_many :posts

    accepts_nested_attributes_for :account

    def full_name
      "#{name} #{surname}"
    end

    def dribble
      JSON.parse(account.contacts.to_s)&.dig('dribble')
    end

    def youtube
      JSON.parse(account.contacts.to_s)&.dig('youtube')
    end

    def twitter
      JSON.parse(account.contacts.to_s)&.dig('twitter')
    end

    def linkedln
      JSON.parse(account.contacts.to_s)&.dig('linkedln')
    end

    def to_param
      name
    end
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
    STATUS = { active: 'актуально', inactive: 'не актуально' }.freeze
    GRADE = { intern: 'стажер', junior: 'джуниор', middle: 'миддл', senior: 'сеньор'}.freeze
    OCCUPATION_TYPE = { full_time: 'полная занятость', part_time: 'частичная занятость', temporary: 'временная', internship: 'стажировка', project: 'проект' }.freeze
    REMOTE = { true => "Удаленная", false => "Офис" }

    belongs_to :account
    has_many :city_vacancies, class_name: 'CityVacancy'
    has_many :cities, through: :city_vacancies

    has_many :skill_vacancies, class_name: 'SkillVacancy'
    has_many :skills, through: :skill_vacancies

    # accepts_nested_attributes_for :skill_vacancies, :city_vacancies

    def company
      account.company
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  # protect_from_forgery with: :null_session

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    vacancies_path
  end

  def after_sign_up_path_for(resource)
    vacancies_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      user_attributes: [
        :name
      ]
    ])
  end

  def current_user
    @current_user ||= current_account.user if account_signed_in?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index; end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.save
    head :ok
    #   redirect_to current_user, notice: 'post was successfully created.'
    # else
    #   render :new, alert: @post.errors
    # end
  end

  def destroy
    post = Post.find_by(id: params[:id])
    post.destroy

    redirect_to current_user, notice: 'post was successfully destroyed.'
  end

  private

  def post_params
    params.permit(
      :title, :text, :url, :image
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user, only: [:edit, :update]

  def show
    @user = User.find_by(name: params[:name])
    @account = @user.account

    @posts = @user.posts
    @current_user = current_account.user
  end

  def edit
    @user_json = UserSerializer.new(@user).to_json
  end

  def update
    user.update(user_params.except(:email)) && user.account.update(email: user_params[:email])
  end

  private

  def user
    @user = User.find_by(name: params[:name])
  end

  def user_params
    params.required(:user).permit!
  end

  def authorize_user
    if current_user&.id != user.id
      flash[:error] = 'Вы можете редактировать только свой профиль.'
      redirect_to root_path and return
    end
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  def index
    @vacancies = Vacancy.all
  end

  def new
    @vacancy = Vacancy.new
  end

  def show
    @vacancy = Vacancy.find(params[:id])
  end

  def create
    @vacancy = current_account.vacancies.new(vacancy_params)

    if @vacancy.save
      redirect_to @vacancy, notice: 'vacancy was successfully created.'
    else
      render :new, alert: @vacancy.errors
    end
  end

  def vacancy_params
    params.require(:vacancy).permit(:id, :title, :description, :salary, :remote, :occupation_type, :account_id,
      city_vacancies_attributes: [:vacancy_id, :city_id],
      skill_vacancies_attributes: [:vacancy_id, :skill_id]
    )
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def parsed_contacts(contacts_json)
    return [] if contacts_json.blank?
    
    JSON.parse(contacts_json)
  end

end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/events/_event_card.html.slim
.h2

app/views/events/_event_main.html.slim
.h1.grey1 Встречайся, общайся

.height-2rem

.menu_search2
  i.search
  input.search_input placeholder='Поиск'

app/views/events/index.html.slim
.event_main
  = render partial: "event_main"

app/views/examples/buttons.html.slim
.l_button.green_button.width-huge action
.s_button.green_button.width-huge action
.s_button.black_button.width-huge action
.l_button.green_button.fit-content action

app/views/examples/cards.html.slim
.card.width-very-huge
    h2.grey1 Заголовок
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Urna aliquam, nisi purus erat enim id in tempor, vitae. Augue fames ac velit vulputate adipiscing. Diam tellus pretium, viverra nullam. Pellentesque neque, netus felis in urna risus nisl. Justo dui, proin massa sollicitudin ut eu sed vivamus. In egestas feugiat feugiat et sollicitudin magnis. Nunc interdum habitant pretium cras. Interdum quam aliquam at nunc sollicitudin. Aliquam urna ut et dictum. Ornare.

.card.width-xxxxl.actionlink
    = image_tag "banner.svg", class: 'banner'
    h2 Купить гараж
    p Бесплатно, без регистрации и смс**

.card.width-xxxxl
    = image_tag "userImage1.svg", class: 'banner'

    h2.grey1 Урааа, авввардз!
    p Мой проект «Красная пыль» получил ленточку в awwards

app/views/examples/input.htlm.slim
input id="vehicle1" name="input" class="input" placeholder="Заполни эту хрень"

= text_area :post, :title, class: "input"

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Предлагать варианты без оплаты

.menu_search
  i.search
  input.search_input placeholder='Поиск'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ADC
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  body
    .menubar
      .menu_items_left
        = link_to root_path do
          .menu-logo
          .width-xxs
          h4.grey1 ADC

        .width-xxs
        h4.green •
        .width-xxs
        = link_to 'CAREER', vacancies_path, class: "footnote grey1 carrer"
        .width-2rem
        //= link_to 'MAIN', root_path , class: "footnote grey1 main"
        //.width-2rem
        - if account_signed_in? && current_account.user.present?
          = link_to 'ME', current_account.user , class: "footnote grey1 me"
        - else
          = link_to 'ME', root_path , class: "footnote grey1 me"
        .width-2rem
        = link_to 'EVENTS', events_path , class: "footnote grey1 main"
        .width-2rem
        //= link_to 'YOURNAME', vacancies_path, class: "h4 grey3 yourname"
      //  .width-2rem
        //= link_to 'BOOKMARKS', vacancies_path, class: "h4 grey3 bookmarks"

      .menu_items_right
        - if account_signed_in?
          = link_to 'Добавить вакансию', new_vacancy_path, class: 'menu_item s_button black_button fit-content'
          .width-1rem
          = link_to 'Выход', destroy_account_session_path, method: :delete, class: 'menu_item s_button black_button fit-content'
        - else
          .width-1rem
          = link_to 'Вход', new_account_session_path, class: 'menu_item s_button black_button fit-content'

    - if container_name = controller_name.in?(%w[sessions registrations passwords]) ? "device_container" : "container"

    - if controller_name.in?(%w[sessions registrations passwords])
      .device_container
        = yield
    - else
      .container
        = flash.each do |type, msg|
          div = msg
        = yield
      footer.footer
        .footnote.grey2.padding_l © ADC (2022)

        .info
          p О нас
          p Конфиденциальность
          p Поступление
          p Сотрудничество

app/views/pages/_about_me.html.slim
.card-me-about.width-xxxxl

  = image_tag "ava.svg", class: 'avatar'
  .height-1rem

  h2.grey1 Артем Кубик

  p.grey2 @artemkubic

  .height-1rem

  .l_button.link_button.width-20rem Link

  .height-1rem

  .l_button.link_button.width-20rem Link

  .height-1rem

  .l_button.link_button.width-20rem Link

  .height-1rem

.height-l

.card-me-about-social.width-21rem
 i.behance
 i.telegram
 i.dribble
 i.vk
 i.youtube
 //i.twitter
 //i.linkedln

.l_button.link_button.width-20rem Link

app/views/pages/_portfolio_me.html.slim
.card-image-h2-me.width-xxxxl
  .img

  h2.grey1 Blopp
  .height-0.5rem
  p Мой проект «Красная пыль» получил ленточку в awwards
  
height-1rem


.card-text-me.width-xxxxl
  h2.grey1 Привет!
  p Ищу ребят для HSE ADC, рарабатываем огненный курс!

height-1rem

  h2.grey1 Навыки
  .height-0.5rem
  p UX/UI
  p UX/UI


//.card.width-xxxxl
    //= image_tag "banner.svg", class: 'banner'
    //h2 Урааа, авввардз!
    //p Мой проект «Красная пыль» получил ленточку в awwards

app/views/pages/home.html.slim
.radio
  .radio__1
    input id="radio-1" type="radio"  name="radio" value="false"
    label for="radio-1"
    .p.red Hello friend

  .radio__2
    input id="radio-2" type="radio" name="radio" value="true" checked=true
    label for="radio-2"
    .p.red Buy friend

  .radio__3
    input id="radio-3" type="radio" name="radio" value="false"
    label for="radio-3"
    .p.red Buy friend

app/views/posts/new.html.slim
= javascript_pack_tag 'event_pack'

.form.images data-props={ user_name: @user.name, new_post: { title: nil, url: nil, text: nil }, image_1: image_url('post_type1'), image_2: image_url('post-type2'), image_3: image_url('post_type3') }.to_json




//.height-4rem



//= form_for @post, url: { action: "create" }, authenticity_token: false, html: { class: 'form' } do |f|
//  .base_info
//    = f.text_field :title, class: "input h1 grey1", placeholder: "Заголовок", autocomplete: 'off'

//    .height-2rem
//    h3.grey1 О проекте*

//    .height-1rem


//    = f.text_area :text, class: "input", placeholder: "Введите текст"

//    .height-2rem

//    h3.grey1 Ссылка*

//    .height-1rem

//    = f.text_area :url, class: "input", placeholder: "http://"

//    .height-2rem

//    h3.grey1 Изображение*

//    .height-1rem

//    = f.file_field :image, class: "input"

//    .height-l

//    .buttons.inline
//      = link_to "Назад", root_path, class: "s_button black_button fit-content"
//      .width-2rem
//      = f.submit "Опубликовать", class: 's_button green_button fit-content'

//.height-4rem

app/views/users/_about_me.html.slim
.card-me-about.width-xxxxl

  = image_tag (@account.image.url || "ava.svg"), class: 'avatar'
  .height-1rem

  h2.grey1 = @user.full_name

  p.grey2 = @account.url




  - @account.contacts&.each do |_app, link|
    - if link.present?
      .height-1rem
      - host = URI(link).host

      .l_button.link_button2.width-20rem
        = link_to host, link, target: '_blank', class: "#{_app}-social-link"

.height-l

.l_button.link_button.width-21rem = link_to 'изменить данные о себе', edit_user_path(@current_user)

.height-l


.card-me-about-social.width-21rem
  - unless @account.behance.blank?
    a href="#{@account.behance}" target="_blank"
      i.behance
  - unless @account.telegram.blank?
    a href="#{@account.telegram}" target="_blank"
      i.telegram
  - unless @account.dribble.blank?
    a href="#{@account.dribble}" target="_blank"
      i.dribble
  - unless @account.vk.blank?
    a href="#{@account.vk}" target="_blank"
      i.vk
  - unless @account.youtube.blank?
    a href="#{@account.youtube}" target="_blank"
      i.youtube

.height-1rem


- if @current_user.present? && @current_user.id == @user.id


  .l_button.link_button.width-21rem = link_to 'добавить карточку', new_post_path
  .height-1rem

app/views/users/_portfolio_me.html.slim
- @posts.each do |post|
  .card-image-h2-me.width-xxxxl
    - if post.image.present?
      .img
        = image_tag post.image.url
    - if post.title.present?
      h2.grey1 = post.title
      .height-0.5rem
    - if post.text.present?
      p = post.text
    .height-0.5rem
    - if @current_user == post.user
      = link_to 'удалить', post, method: :delete

.height-2rem


.card-image-h2-me.width-xxxxl
  .img

  .h2.grey1 Привет!
  .height-0.5rem
  p Добавьте свою первую карточку

.height-2rem




//.card.width-xxxxl
    //= image_tag "banner.svg", class: 'banner'
    //h2 Урааа, авввардз!
    //p Мой проект «Красная пыль» получил ленточку в awwards

app/views/users/edit.html.slim
//= javascript_pack_tag 'user_form_pack'

//.height-4rem

//.form.user_form data-props=@user_json


.height-4rem

= form_for @user, url: { action: "update" }, authenticity_token: false, html: { class: 'form edit_form' } do |f|
  .base_info
    h1.grey1 Редактирование профиля

    .height-2rem

    h3.grey1 Никнейм
    .height-1rem

    = f.text_field :name, class: "input button grey2 width-very-big", placeholder: "Имя", autocomplete: 'off'

    .height-l

    h3.grey1 Должность
    .height-1rem

    = f.text_field :surname, class: "input button grey2 width-very-big", placeholder: "Фамилия", autocomplete: 'off'

    .height-l

    .h2.grey1 Социальные сети

    .height-1rem

    = f.fields_for :account, @user.account do |subform|
      = subform.fields :socials, model: OpenStruct.new(subform.object.socials) do |field|

        .inline
          i.vk-small
          .width-1rem
          = field.text_field :vk, class: "input button grey2 width-huge"

        .height-1rem

        .inline
          i.telegram-small
          .width-1rem
          = field.text_field :telegram, class: "input button grey2 width-huge"

        .height-1rem


        .inline
          i.dribble-small
          .width-1rem
          = field.text_field :dribble, class: "input button grey2 width-huge"

        .height-1rem

        .inline
          i.behance-small
          .width-1rem
          = field.text_field :behance, class: "input button grey2 width-huge"

        .height-1rem


        .inline
          i.youtube-small
          .width-1rem
          = field.text_field :youtube, class: "input button grey2 width-huge"

        .height-1rem


        .inline
          i.twitter-small
          .width-1rem
          = field.text_field :twitter, class: "input button grey2 width-huge"

        .height-1rem


        .inline
          i.linkedln-small
          .width-1rem
          = field.text_field :linkedln, class: "input button grey2 width-huge"

    .height-l

    .height-xxs


    = f.fields_for :account, @user.account do |subform|
      .h2.grey1 Обновить фото


      .height-1rem

      = subform.file_field :image, class: "input"

      .height-xl

      .h2.grey1 Ссылки
      .height-1rem


      = subform.fields :contacts, model: OpenStruct.new(subform.object.contacts) do |field|
        h3.grey1
        = field.text_field :link_1, class: "input button grey2 width-very-big"

        .height-s



        h3.grey1
        = field.text_field :link_2, class: "input button grey2 width-very-big"

        .height-s



        h3.grey1
        = field.text_field :link_3, class: "input button grey2 width-very-big"

        .height-s




    .height-l

    .buttons.inline
      = link_to "Назад", root_path, class: "s_button black_button fit-content"
      .width-2rem
      = f.submit "Опубликовать", class: 's_button green_button fit-content'

.height-4rem

app/views/users/show.html.slim
.about_me
  = render partial: "about_me"

.width-6rem

.portfolio_me
  = render partial: "portfolio_me"

app/views/vacancies/_filter.html.slim
h2.grey1 Сфера
.height-xs

.menu_search
  i.search
  input.search_input placeholder='Поиск'

.height-2rem

// Зарплата
.h2.grey1 Зарплата
.height-xs |
.inline
  input.width-xxl id="vehicle1" name="input" class="input" placeholder="от 3000"
  .width-1rem
  input.width-xxl id="vehicle1" name="input" class="input" placeholder="до 200 000"

.height-xs

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Предлагать варианты без оплаты
.height-2rem

// Вид
h2.grey1 Вид
.height-xs

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Вакансии

.height-xs

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Стажировки
.height-2rem

// Занятость
h2.grey1 Занятость
.height-xs

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Вакансии

.height-xs


.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Проекты

.height-xs

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Временные стажировки
.height-2rem

// Удалёнка
h2.grey1 Удалёнка
.height-xs

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Онлайн

.height-xs


.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Оффлайн / смешанный
.height-2rem

// Опыт работы
h2.grey1 Опыт работы
.height-xs

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Без опыта

.height-xs

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Менее 1 года

.height-xs

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" 1-2 года

.height-xs

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" 3-4 года

.height-xs

.check_box
  = check_box_tag 'receive_email', 'yes', true, class: 'box'
  .width-1rem
  label.button.grey1 for="checkbox" Более 5 лет

app/views/vacancies/_vacancy_card.html.slim
= link_to vacancy_path(vacancy.id), class: "card card-vacancy grey2 width-20rem" do
    .logo
        - if vacancy.account.image.present?
          = image_tag(vacancy.account.image.url)
        - else
          img.avatar
        .width-xs
        - if vacancy.account.company.present?
          .button #{ vacancy.account.company.name }
        - if vacancy.account.user.present?
          .button #{ vacancy.account.user.name }

    .height-xs

    h3.grey1 #{ vacancy&.title }
    .height-xxxs
    .info
        p.footnote #{ Vacancy::OCCUPATION_TYPE[vacancy&.occupation_type&.to_sym] }
        - vacancy&.cities&.each do |city|
          p.footnote
              span •
              | #{ city&.name }

    .height-s
    p.grey1 #{ number_to_currency(vacancy&.salary, delimiter: " ", precision: 0, unit: "₽ / мес", format: "%n %u") }

    .height-xs
    .tags
        .tag.s_button.fit-content.green #{ Vacancy::GRADE[vacancy&.grade&.to_sym] }
        .width-xs

app/views/vacancies/index.html.slim
= image_tag "banner.svg", class: 'banner'

.filter.width-16rem
  = render partial: "filter"

.width-6rem

.vacancies
  = render partial: "vacancy_card", collection: @vacancies, as: :vacancy

app/views/vacancies/new.html.slim
.height-4rem
= form_for @vacancy, url: { action: "create" }, authenticity_token: false, html: { class: 'form' } do |f|
  .base_info
    = f.text_field :title, class: "input p grey1", placeholder: "Название вакансии", autocomplete: 'off'

    .height-2rem
    h3.grey1 О стажировке*

    .height-1rem


    = f.text_area :description, class: "input", placeholder: "Введите текст"

    .height-2rem

    h3.grey1 Оплата*

    .height-1rem

    = f.text_field :salary, class: "input", placeholder: "₽"

    .height-1rem

    .check_box
      = check_box_tag 'receive_email', 'yes', false, class: 'box'
      .width-1rem
      label.button.grey1 for="checkbox" На собеседовании

    .height-1rem

    .check_box
        = check_box_tag 'receive_email', 'yes', false, class: 'box'
        .width-1rem
        label.button.grey1 for="checkbox" Без оплаты

    .height-2rem


    h3.grey1 Обязанности кандидата*

    .height-1rem

    = f.text_area :description, class: "input", placeholder: "Введите текст"


    .height-2rem


    h3.grey1 Критерии для кандидата*

    .height-1rem

    = f.fields_for :skill_vacancies, @vacancy.skill_vacancies.build do |subform|
      = subform.hidden_field :vacancy_id, value: f.object.id
      = subform.select(:skill_id, options_for_select(Skill.all.pluck(:name, :id)), { include_blank: "Критерии для кандидата*" }, { class: 'input' })

    .height-2rem



    .height-1rem

    input id="vehicle1" name="input" class="input" placeholder="Email"

    .height-1rem

    .check_box
        = check_box_tag 'receive_email', 'yes', false, class: 'box'
        .width-1rem


        label.button.grey1 for="checkbox" На почту указанную при регистрации


  .properties.width-xxxxl.card

    .footnote.grey1 Формат*

    .height-xxs
    - remote = { "офис": false, "удаленка": true }
    = f.select(:remote, options_for_select(remote), { include_blank: false }, { class: 'input' })

    .height-l

    .footnote.grey1 График*

    .height-xxs

    = f.select(:occupation_type, options_for_select(Vacancy::OCCUPATION_TYPE.invert), { include_blank: false }, { class: 'input' })

    .height-l

    .footnote.grey1 Город*

    .height-xxs

    = f.fields_for :city_vacancies, @vacancy.city_vacancies.new  do |subform|
      = subform.hidden_field :vacancy_id, value: f.object.id
      = subform.select(:city_id, options_for_select(City.all.pluck(:name, :id)), { include_blank: "" }, { class: 'input' })

    .height-l

    .buttons.inline
      = link_to "Назад", root_path, class: "s_button black_button fit-content"
      .width-2rem
      = f.submit "Опубликовать", class: 's_button green_button fit-content'

.height-4rem

app/views/vacancies/show.html.slim
.vacancy
  .base_info.width-48rem
    .footnote ADC Space — Стажировки
    .height-1rem
    h1.grey1 #{ @vacancy.title }
    .height-1rem
    .logo
        - if @vacancy.account.image.present?
          = image_tag(@vacancy.account.image.url)
        - else
          img.avatar
        .width-xs
        - if @vacancy.account.company.present?
          .button #{ @vacancy.account.company.name }
        - if @vacancy.account.user.present?
          .button #{ @vacancy.account.user.name }

    .height-2rem
    .card
        h2.grey1 О стажировке
        p #{ @vacancy.description }
    .height-2rem

    .card
        h2.grey1 О компании
        p #{ @vacancy.description }
    .height-2rem

    .card
        h2.grey1 Критерии кандидата
        - @vacancy.skills.pluck(:name).each do |skill |
          p #{ skill }

  .width-2rem

  .properties.width-huge.card
    .footnote.grey2 Формат*
    .height-xxs
    h3.grey1.inline
      i.bus
      .width-xxs
      |
        #{ Vacancy::REMOTE[@vacancy.remote] }

    .height-xxs

    .height-l

    .footnote.grey2 График*
    .height-xxs

    h3.grey1.inline
      i.clock
      .width-xxs
      |
        #{ Vacancy::OCCUPATION_TYPE[@vacancy.occupation_type.to_sym]}

    .height-xxs


    .height-l

    .footnote.grey2 Город*
    .height-xxs
    - @vacancy.cities.pluck(:name).each do |city|
      h3.grey1.inline
        i.location
        .width-xxs

        |
          #{ city }

    .height-l


    .footnote.grey2 Зарплата*
    .height-xxs
    h3.grey1.inline
      i.money
      .width-xxs
      |
        #{ @vacancy.salary}


    .height-l

    .s_button.green_button.width-20rem Откликнуться